import Head from "next/head";
import Link from "next/link";
import { gql } from "@apollo/client";
import { client } from "../lib/apollo";
import "bootstrap/dist/css/bootstrap.min.css";
import NavigationBar from "./components/NavigationBar";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Wordpress Site</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
      <NavigationBar />
      <div className="container bg-dark text-light">
        <main className="main">
          <div>
            <div className="d-flex justify-content-center flex-column">
              <h1 className="no-wrap m-auto mt-5">My Wordpress site!</h1>

              <ul className="m-auto mt-3">
                {console.log(posts)}
                {posts.map(({ postId, slug, title, content }) => (
                  <li key={postId}>
                    <h4>
                      <Link href={`blog/${slug}`}>
                        <a>{title}</a>
                      </Link>
                    </h4>
                    <div
                      dangerouslySetInnerHTML={{
                        __html: content,
                      }}
                    ></div>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const result = await client.query({
    query: gql`
      query GetWordPressPosts {
        posts {
          nodes {
            postId
            title
            uri
            slug
            excerpt
            date
            content
          }
        }
      }
    `,
  });

  return {
    props: {
      posts: result.data.posts.nodes,
    },
  };
}
